### ISSUE TITLE
Ревизия ошибок в указании синтаксиса `code-block`

### ISSUE THREAD

**Issue by OlegShchavelev** [OlegShchavelev/ALTGnomeWiki#127]
При запуске проекта локально:
`The language 'patch' is not loaded, falling back to 'txt' for syntax highlighting.`

Необходимо обсудить метод дебагинга данного типа ошибок.

**Comment by Ampernic** [comment]
> Необходимо обсудить метод дебагинга данного типа ошибок.

Не совсем понимаю о каком методе дебагинга тут речь
Это в сути своей предупреждение о том, что человек указал для блока кода неизвестный для Shiki язык и он будет отображен как обычный блок txt.

Дебаг тут прост: есть предупреждение - исправь

А для профилактики можно [ознакамливать авторов со списком поддерживаемых ситаксисов shiki](https://shiki.style/languages) в разделе для авторов
Если синтаксиса нет, а он нужен:
- Ищем близкий по подсветке
- Просим добавить у [нас](https://github.com/OlegShchavelev/ALTGnomeWiki/issues) / [Shiki](https://github.com/shikijs/shiki/issues)

(Опыт с таки добавлением был в b293a9a873bf05d2d43611e812417a7a183ce2a6, а потом синтаксис был добавлен и в сам Shiki)

**Comment by Ampernic** [comment]
Теперь подобного рода ошибки можно выявлять через

```shell
npm run docs:remark--full
```

Это решает задачу?

**Comment by OlegShchavelev** [comment]
> Теперь подобного рода ошибки можно выявлять через
> 
> ```shell
> npm run docs:remark-full
> ```
> 
> Вынес правило в npm пакет `@ampernic/remark-lint-shiki-code-block-syntax-exist` для переиспользования на других проектах.
> 
> Это решает задачу?

Безусловно!

Я проверил, это работает:

```shell
docs/apps/boxes.md
54:1-57:4 warning txt not exist or not supported by shiki shiki-code-block-syntax-exist remark-lint
```
