### ISSUE TITLE
Автоматизация текстовых блоков установки в разделе "Установка и обновление программ".

### ISSUE THREAD

**Issue by OlegShchavelev** [OlegShchavelev/ALTGnomeWiki#161]
Это проблема в формате обсуждения, преамбула обсуждения.

Завести вставки с шаблонными переменными:
install-repo.md
install-flatpak.md
install-snap.md
install-appimage.md

Подробнее в документации:
https://vitepress.dev/guide/markdown#markdown-file-inclusion

Продумать семантику шаблонных переменных, что бы избежать их дублирование при создании новых блоков и интерфейсов.
К примеру:
https://github.com/OlegShchavelev/ALTRegularGnomeWiki/issues/129

**Comment by OlegShchavelev** [comment]
Данную историю откладываем, после навигации. Проблема с парсингом ключевых переменных. Очень длинная получится историю. 

Нашел компонент:

**Comment by OlegShchavelev** [comment]
@OlegShchavelev Это историю мы откладываем. Очень муторная история.

**Comment by fiersik** [comment]
@OlegShchavelev Инструкцию в разделе для авторов я тогда откачу (завтра - послезавтра)

**Comment by Ampernic** [comment]
Закрыто в PR #(где-то на задворках истории)
