### ISSUE TITLE
Добавить боковой бар для раздела «Расширения рабочего окружения GNOME»

### ISSUE THREAD

**Issue by OlegShchavelev** [OlegShchavelev/ALTGnomeWiki#329]
Необходимо продумать данные в frontmatter и как расширить возможности модуля AGWDocsAsideMeta.vue

**Comment by OlegShchavelev** [comment]
@X1Z53, обсудили, что ISSUE закроешь ты)

**Comment by Ampernic** [comment]
Закрыто @X1Z53 в PR #525
