### ISSUE TITLE
Не очевидная очистка всех загрузочных разделов

### ISSUE THREAD

**Issue by zerocomputer** [OlegShchavelev/ALTGnomeWiki#34]
Только вчера поставил себе ALT Regular Gnome.

После завершения установки и перезагрузки, вылезло окно на пару секунд, вида DOS, где было написано, что-то в духе "Reset boot". В общем, я не успел понять что происходит, в итоге на соседнем диске снес загрузочный раздел Windows. 

Неприятная ситуация, как восстановить не знаю.

**Comment by OlegShchavelev** [comment]
@zerocomputer 
Безусловно необходимо две мощных страницы:

* Подробный мануал по установке системы во всех возможных вариантах: одна система, несколько систем (dual boot)
* Реконфигурация или восстановление Grub установщика

Сейчас из более или менее актуального:
https://plafon.gitbook.io/alt-zero/alt-zero/start/ustanovka

В течение 1-2 недели добавим на Wiki вышеизложенные материалы.

**Comment by Ampernic** [comment]
> @zerocomputer Безусловно необходимо две мощных страницы:
> 
>     * Подробный мануал по установке системы во всех возможных вариантах: одна система, несколько систем (dual boot)
> 
>     * Реконфигурация или восстановление Grub установщика
> 

Вынесено в
#541 - `Лонг-рид по установке ALT Regular **Gnome`
#540 - `Лонг-рид по GRUB`

**Comment by Ampernic** [comment]
> > @zerocomputer Безусловно необходимо две мощных страницы:
> > ```
> > * Подробный мануал по установке системы во всех возможных вариантах: одна система, несколько систем (dual boot)
> > 
> > * Реконфигурация или восстановление Grub установщика
> > ```
> 
> Вынесено в #541 - `Лонг-рид по установке ALT Regular Gnome` #540 - `Лонг-рид по GRUB`

Закрыто
Перенесено в более глобальные issue #541 и #540
