### ISSUE TITLE
carousel галерея: сжатие изображений 

### ISSUE THREAD

**Issue by fiersik** [OlegShchavelev/ALTGnomeWiki#349]
При использование галереи типа `carousel` изображение слишком сильно сжимается.

![IMG_20240505_015006_737](https://github.com/OlegShchavelev/ALTGnomeWiki/assets/131641124/c3f4742f-cf54-4a0b-a426-54540254bdb0)

![S40505-02321682](https://github.com/OlegShchavelev/ALTGnomeWiki/assets/131641124/92f7a382-5484-4433-8ac0-cd1a4d346500)

**Comment by Ampernic** [comment]
> При использование галереи типа `carousel` изображение слишком сильно сжимается.

На самом деле оно не сжимается, оно обрезается и это скорее специфика типа, которую стоит учитывать при выборе типа галереи.
![изображение](https://github.com/user-attachments/assets/0d7e399d-7fbe-4fb5-8305-1b1e1a5954bd)

Сжатие выглядело бы так 
![изображение](https://github.com/user-attachments/assets/e10df90d-6db6-49ac-814f-736e727a28e7)

А без обрезки это выглядит как то так
![изображение](https://github.com/user-attachments/assets/ba62400e-fadf-480a-871d-cf8373b75764)

Так что думаю wontfix так сказать..
Думаю стоит уточнить у @OlegShchavelev

**Comment by OlegShchavelev** [comment]
@Ampernic это не сжатие, а ориентация (Ratios), подробнее можно почитать:
https://getbootstrap.com/docs/5.3/helpers/ratio/#aspect-ratios

**Comment by Ampernic** [comment]
> @Ampernic это не сжатие, а ориентация (Ratios), подробнее можно почитать: https://getbootstrap.com/docs/5.3/helpers/ratio/#aspect-ratios

Я понимаю, речь сейчас о том что проблема ли это

**Comment by Ampernic** [comment]
> > > @Ampernic это не сжатие, а ориентация (Ratios), подробнее можно почитать: https://getbootstrap.com/docs/5.3/helpers/ratio/#aspect-ratios
> > 
> > 
> > Я понимаю, речь сейчас о том что проблема ли это
> 
> Я думаю, что для центрированных скриншотов основного окна интерфейса, которое не очень большое, можно использовать ориентацию 1x1 с масштабированием cover, особенно если изображений много.

Я об этом и говорю, что в сути своей это не проблема.

В сути своей ишью о том что изображение "сжимается" и это проблема.
А это не так. Это специфика типа галереи. У нас есть ишью https://github.com/OlegShchavelev/ALTGnomeWiki/issues/81 в котором написано:

> carousel — это галерея, которая отображается через библиотеку Swiper. На мобильных устройствах мы показываем 1,2 изображения, на планшетах — 3, а на остальных устройствах — 4 в видимой зоне.

И она свою задачу выполняет так, как написано и конкретный пример - это просто неудачный выбор типа для содержимого.
(В этом я с кириллом согласен, маленький 1x1 смотрится станновато для FHD скриншота, особенно когда он 1)
![изображение](https://github.com/user-attachments/assets/fd025367-4c20-46cc-9d71-56f8a46d50da)

**Comment by Ampernic** [comment]
NotABug

Закрываем за отсутствием обсуждения.
Можем открыть повторно при ответе на сообщение выше.
