### ISSUE TITLE
Яркий блок спонсоров при наведении

### ISSUE THREAD

**Issue by X1Z53** [OlegShchavelev/ALTGnomeWiki#356]
В тёмной теме на главное странице при наведении на блок спонсоров, карточки становятся белыми из светлой темы

**Comment by Ampernic** [comment]
> В тёмной теме на главное странице при наведении на блок спонсоров, карточки становятся белыми из светлой темы

Не уверен в том что это проблема
Когда-то выдвигал предположение, что это сделано специально, т.к. на белом любой логотип будет выглядеть так, как его задумал автор/дизайнер, а при попытке изменить фоновый цвет определенные детали могут теряться на фоне карточки.
У нас уже был опыт изменения этого цвета на другой, но итоговый вариант выглядел грязновато.

Тут вопрос больше к гайдам дизайнеров, коим я не являюсь, но слышал о подобных решениях.

**Comment by Ampernic** [comment]
Думаю пока закроем за отсутвием обсуждения.
При наличии новых деталей и мыслей можно открыть снова.
