### ISSUE TITLE
Кнопки GitFlic

### ISSUE THREAD

**Issue by X1Z53** [OlegShchavelev/ALTGnomeWiki#359]
На карточках контрибьтеров не работают ссылки на ресурс GitFlic

**Comment by OlegShchavelev** [comment]
@X1Z53 ссылки поправились?

**Comment by Ampernic** [comment]
> @X1Z53 ссылки поправились?

Должны были, просто ему повезло ткнуть именно на тебя и фиерсика.... А у вас сама ссылка не была написана)

**Comment by OlegShchavelev** [comment]
@Ampernic Тогда поправились. Спасибо.
