### ISSUE TITLE
[ Docs ] Автоматическое заполнение версии Vitepress

### ISSUE THREAD

**Issue by Ampernic** [OlegShchavelev/ALTGnomeWiki#489]
![image](https://github.com/OlegShchavelev/ALTGnomeWiki/assets/44705058/07ba28f6-4a41-4ef0-9f10-ba796a0843ce)

>Олег Щавелев, [7/9/24 9:22 PM]
>Надо сделать автоматически, что бы не забывать. Где-то об этом было написано!
>
>Олег Щавелев, [7/9/24 9:22 PM]
>Я буду благодарен если ты в этом разберешся. Отличная задача для старта.
>
>Олег Щавелев, [7/9/24 9:23 PM]
>Возможно есть ISSUE если нет поставь пожалуйста.

@X1Z53 Простая задача, можешь взяться

**Comment by X1Z53** [comment]
@Ampernic 👌
