### ISSUE TITLE
На странице приложение реализовать возможность указывать отдельно ID приложения и ссылку на репозиторий.

### ISSUE THREAD

**Issue by OlegShchavelev** [OlegShchavelev/ALTGnomeWiki#510]
В репозитории «Сизиф» есть пакеты, названия которых в RPM-пакетах и SRPMS могут отличаться. Например, пакет с названием «gnome-shell» содержит несколько пакетов:

- gnome-shell
- gnome-extensions-app

Предлагаю ввести возможно указывать URL на пакет отличающий от его ID и следующий вариант frontmatter

```md
sisyphus:
    id: gnome-extensions-app
    link: sisyphus/srpms/gnome-shell
```

**Comment by X1Z53** [comment]
@OlegShchavelev А нам нужно, чтобы люди прописывали это полностью? Вроде все всё из sisyphus/srpms берут

**Comment by Ampernic** [comment]
Есть какие-то нюансы или могу закрыть?

**Comment by Ampernic** [comment]
👌
