### ISSUE TITLE
[ Contest - @X1Z53 ] Добавить возможность использования "блока-ссылки" (feat. @chodocs)

### ISSUE THREAD

**Issue by X1Z53** [OlegShchavelev/ALTGnomeWiki#537]
**Закреплено за @X1Z53**

Создание опциональной разметки (в формате md) для отображения ссылок в виде информеров:

Пример с [ChoDocs](https://chodocs.cn/program/npm-package/)

![image](https://github.com/user-attachments/assets/e98d4da3-b4fe-4f3e-bd0c-6fa5103cda8a)

**Comment by Ampernic** [comment]
Добавлено PR #549
Завершено в PR #550
