### ISSUE TITLE
[ Markdown ] Внедрение плагина `@nolebase/vitepress-plugin-enhanced-mark`

### ISSUE THREAD

**Issue by Ampernic** [OlegShchavelev/ALTGnomeWiki#556]
Страница плагина: https://nolebase-integrations.ayaka.io/pages/en/integrations/vitepress-plugin-enhanced-mark/

**Comment by X1Z53** [comment]
@Ampernic Ничего не знаю

**Comment by Ampernic** [comment]
Выполнено в PR #557
