### ISSUE TITLE
[ Docs ] Дополнить информацию об установке расширений

### ISSUE THREAD

**Issue by Ampernic** [OlegShchavelev/ALTGnomeWiki#558]
Евгений Чернышев пишет

>https://docs.google.com/document/d/10lm3XyQ0MA3PT6EjNvErfcUIHJpwfSkkv0xhU5r6Yn0/edit?usp=sharing
Вроде, доступно все описал.

**Comment by OlegShchavelev** [comment]
@Ampernic, спасибо, что зафиксировал ISSUE. Документ прочитал и внес в документации с улучшением и коррекцией e1372fa4be6aa9f095fe21c2e8d9e6ad7d67399a.
