### ISSUE TITLE
Исключение из поиска служебных страниц

### ISSUE THREAD

**Issue by X1Z53** [OlegShchavelev/ALTGnomeWiki#559]
В разделах `_parts` существуют шаблонные `md`-файлы, которые попадают как в индексацию поисковых систем, так и внутреннего поиска сайта

Во избежание этого можно переименовать соответствующие разделы из `_parts` в `.parts`

**Comment by OlegShchavelev** [comment]
@X1Z53 Если грубо ты все правильно написал

**Comment by Ampernic** [comment]
Ршается даже без переименования добавлением ключа фронтматтер
![изображение](https://github.com/user-attachments/assets/e165a75d-7bae-4d9e-bce5-09d9bd3f4a00)

Из поисковой выдачи они давно закрыты
![изображение](https://github.com/user-attachments/assets/2636c21a-3a97-4893-a3ec-3c89132c827e)

Думаю решено коммитом 94c9e9a
