### ISSUE TITLE
General edits

### ISSUE THREAD

**Issue by pokedim13** [OlegShchavelev/ALTGnomeWiki#57]
Предлагаю внести глобальные общие правки, а именно:

- [x] Добавить методологию **Kanban** для создания задач на основе **issue**. Это позволит упростить работу в команде, так как каждый сможет наглядно видеть, как работает проект, и брать задачи, которые ему подходят. Для этого можно использовать **бота в Telegram**, который будет добавлять задачи в соответствующий список.
<img src="https://github.com/OlegShchavelev/ALTRegularGnomeWiki/assets/72319244/d47cd4c0-8d3d-4834-b932-a45276127136" width="400" height="320" />

#

- [x] Снова... поменять структурный подход, ибо я говорил, там демо больше, и вот сейчас я предлагаю правильный подход. Пример ниже. Это создаст удобную иерархию файлов, а так же позволит добавлять пути вида - /app/guide.html, /app/build.html. Когда основная информация о приложении будет располагаться на /app.html

![Снимок экрана от 2023-11-30 20-54-36](https://github.com/OlegShchavelev/ALTRegularGnomeWiki/assets/72319244/edb70f34-6118-435d-84e3-6c490120cda2)

#

- [x]  Сделать генераторы навигации, и вообще разгрузить конфиг (он у вас слишком жирный), как я сделал генератор rewrites

# 

- [ ] Надо добавить всё же несколько префиксов, ведь когда-нибудь, просто напросто придётся пересесть на uri вида /apps/app.html /system/app.html, /problems/issue.html (Пусть о проблемах знают уже из вики, так для новокеков будет видна работа, что над этим занимаются, а для опытных задача для решения) если, что я могу индексированные страницы исключить из такой иерархии, пока другие страницы не проиндексируются. Вообще проект ток развивается, как я вижу, и если сделать очень подробную вики, люди сами потянутся

# 

- [ ] Пришла в голову идея с  переездом с vitepress на alt_vitepress (Раз я всяко быстрее внедряю что-либо, даже не зная языка)

Жду ответа, и правок от остальных участников

**Comment by OlegShchavelev** [comment]
> Сделать генераторы навигации, и вообще разгрузить конфиг (он у вас слишком жирный), как я сделал генератор rewrites
Это хорошая идея, изначально обсуждали, обязательно реализуем.

**Comment by OlegShchavelev** [comment]
Добавить методологию Kanban для создания задач на основе issue. Это позволит упростить работу в команде, так как каждый сможет наглядно видеть, как работает проект, и брать задачи, которые ему подходят. Для этого можно использовать бота в Telegram, который будет добавлять задачи в соответствующий список.

Спасибо за формализацию проблемы, на мой взгляд это преждевременно. Основная причина: мы не определи основную площадку для проекта.
Безусловно задачу можно дифференцировать и к примеру создать отдельную группу по alt_gnome_wiki и сделать статусы по ISSUE

**Comment by Ampernic** [comment]
Здравствуйте.

Пройдусь по пунктам

>  Добавить методологию Kanban для создания задач на основе issue. Это позволит упростить работу в команде, так как каждый сможет наглядно видеть, как работает проект, и брать задачи, которые ему подходят. Для этого можно использовать бота в Telegram, который будет добавлять задачи в соответствующий список.

На данный момент есть выполненная на основе `GitHub Projects` доска с распределением, как показала практика - такой подход не приживается в комманде, всем проще взаимодейтсвовать в чате. [Доска](https://github.com/users/OlegShchavelev/projects/1)

> Снова... поменять структурный подход, ибо я говорил, там демо больше, и вот сейчас я предлагаю правильный подход. Пример ниже. Это создаст удобную иерархию файлов, а так же позволит добавлять пути вида - /app/guide.html, /app/build.html. Когда основная информация о приложении будет располагаться на /app.html

Данный подход был добавлен до моего прихода в комманду и создал уйму проблем при интеграции различных плагинов.
С одной стороны - можете сказать что это проблема плагинов. Я скажу - проблема подхода, который не популярен, моментами, неуместен.

> Сделать генераторы навигации, и вообще разгрузить конфиг (он у вас слишком жирный), как я сделал генератор rewrites

На данный момент разгрузили конфиги, и генератор навигации на подходе. Подробнее PR #524

> Пришла в голову идея с переездом с vitepress на alt_vitepress (Раз я всяко быстрее внедряю что-либо, даже не зная языка)

Разъясните смысл прехода


_В общем и целом - думаю стоит закрыть ишью т.к. задачи из него или не планируются к выполнению, или выполнены, или отделены на другие задачи._

**Если есть возражения или дополнения - можем открыть заново.**
