### ISSUE TITLE
Неоднородный стиль ввода команд

### ISSUE THREAD

**Issue by Rirusha** [OlegShchavelev/ALTGnomeWiki#579]
Статья: https://alt-gnome.wiki/flatpak.html#запуск-приложении

В первом случае так: 
![image](https://github.com/user-attachments/assets/4c98c7c4-245f-4eaa-b3ea-6153f0fc98d2)
В первом блоке ```su -```. Во втором ```exit```.

Во втором случае так: 
![image](https://github.com/user-attachments/assets/14121468-7d2c-4d6c-b36b-e1cdd95b5481)
Здесь ```su -``` и в первом, и во втором блоке.

Нужно ли разделение на блоки? И почему во втором случае ```su -``` повторяется.

**Comment by X1Z53** [comment]
@Rirusha Возможно потому, что в первом случае su - не требуется, а во втором случае даже с epm su - требуется, но не прописывается в первом блоке

**Comment by X1Z53** [comment]
@Rirusha Предлагаю объединить в один блок, хоть он и будет содержать немного повтора

**Comment by X1Z53** [comment]
@Rirusha Если su - во втором случае не требуется, то можно его оттуда исключить

Также не уверен, что нужен exit

**Comment by OlegShchavelev** [comment]
@Rirusha, @X1Z53, это очень интересная дискуссия. Я благодарен вам за участие.

Мне кажется, некоторые текстовые разделы можно объединить для удобства чтения. Например, если в одном разделе есть несколько блоков с фрагментами кода, и первый требует привилегированных прав, а второй — нет, то в первом блоке можно использовать команду exit. Однако на мой взгляд, это не нужно делать в разных разделах, разделённых подзаголовками.

Я внес изменения коммитом fbd55ff05491b7030eef759dc8b9d54fcb519011, считаете ли вы, что мы решили проблему #579?

**Comment by OlegShchavelev** [comment]
@X1Z53 Спасибо тебе за комментарий. Отличные новости!

**Comment by Rirusha** [comment]
> @Rirusha, @X1Z53, это очень интересная дискуссия. Я благодарен вам за участие.
> 
> Мне кажется, некоторые текстовые разделы можно объединить для удобства чтения. Например, если в одном разделе есть несколько блоков с фрагментами кода, и первый требует привилегированных прав, а второй — нет, то в первом блоке можно использовать команду exit. Однако на мой взгляд, это не нужно делать в разных разделах, разделённых подзаголовками.
> 
> Я внес изменения коммитом [fbd55ff](https://github.com/OlegShchavelev/ALTGnomeWiki/commit/fbd55ff05491b7030eef759dc8b9d54fcb519011), считаете ли вы, что мы решили проблему #579?

Можно ли проверить итоговый вариант без запуска вики локально?

**Comment by X1Z53** [comment]
Да, [результат](https://alt-gnome.wiki/flatpak.html#запуск-приложении) уже опубликован
