### ISSUE TITLE
Исправить `description` страниц

### ISSUE THREAD

**Issue by Ampernic** [OlegShchavelev/ALTGnomeWiki#584]
На данный момент неправильно отображается дата последнего обновления Вики

![Screenshot_20240823-193449~2](https://github.com/user-attachments/assets/c2ada3b5-4c64-4338-929d-bda40bf8ca88)

Проблема актуальна для AGW и AKW, а так же Вики где заимствуется код генерации этого описания. 
Сам займусь этой проблемой, оформляю чтобы не забыть.

**Comment by Ampernic** [comment]
Исправлено в c2d491f

Ждем обновления в течении 2-3 дней, если все в порядке - закрываем ишью

**Comment by OlegShchavelev** [comment]
Работает!
![image](https://github.com/user-attachments/assets/36ac49af-95b5-436d-8ead-9cf63dcc11e0)
