### ISSUE TITLE
Надпись на главной странице

### ISSUE THREAD

**Issue by X1Z53** [OlegShchavelev/ALTGnomeWiki#593]
Изменить надпись на главной странице с `ALT Regular Gnome Community` на `ALT Gnome Community` или, возможно, на `ALT Gnome Wiki`

**Comment by Ampernic** [comment]
@OlegShchavelev я думаю данный вопрос лучше адресовать тебе...

**Comment by OlegShchavelev** [comment]
Я согласен с @X1Z53 в том, что это можно актуализировать. Поскольку название использовалось с самого начала, когда ещё не было точных формулировок, думаю, @X1Z53 может отправить PR с исправлениями.

**Comment by X1Z53** [comment]
> думаю, @X1Z53 может отправить PR с исправлениями.

В таком случае, какой вариант лучше использовать: `ALT Gnome Wiki` или `ALT Gnome Community`?

Мне лично импонирует больше первый, потому что тут именно про Wiki речь

**Comment by OlegShchavelev** [comment]
@X1Z53 Я думаю ALT Gnome Wiki и чуть чуть описание поправить. Можно посмотреть и сделать на подобие ALT Mobile Wiki
https://altmobile.org/

**Comment by Ampernic** [comment]
Выполнено: #610
