### ISSUE TITLE
bug: тег у раздела "История изменений" имеет неправильный формат

### ISSUE THREAD

**Issue by alexei-zebra** [OlegShchavelev/ALTGnomeWiki#604]
Тег у раздела `История изменений` на страницах имеет неправильный формат
![изображение](https://github.com/user-attachments/assets/5a5fee94-299c-48ed-b7ff-525dfe054cd9)
![изображение](https://github.com/user-attachments/assets/b252f921-db5e-4d7b-89fe-b804d5685ef6)

Другие теги имеют коректный формат
![изображение](https://github.com/user-attachments/assets/04201766-dde8-4bde-9144-bfccbe110d97)

**Comment by OlegShchavelev** [comment]
Этот функционал не был создан участниками ALT Gnome Wiki, но он отлично работает, и мы его очень полюбили. Хотя данное замечание имеет право быть.

```shell
"devDependencies": {
    "@nolebase/vitepress-plugin-git-changelog": "^2.4.0"
}
```

https://github.com/nolebase/integrations/blob/main/packages/vitepress-plugin-git-changelog/src/locales/ru-RU.yaml#L3

```yaml
titleId: 'история изменений'
```

Большая просьба, отправьте [ISSUE](https://github.com/nolebase/integrations/issues) автору плагина и (или) отправьте PR. Мы будем очень благодарны.

**Comment by Ampernic** [comment]
Спасибо за ПР в репозиторий автора, прости за задержку, обновил наконец версию пакетов в https://github.com/OlegShchavelev/ALTGnomeWiki/commit/a99b9d019af2c54a6a7e30d36fccc0e8bfa9ffb4
