### ISSUE TITLE
Устаревшая информация на страницу Penpot

### ISSUE THREAD

**Issue by Rirusha** [OlegShchavelev/ALTGnomeWiki#605]
https://alt-gnome.wiki/penpot-desktop.html

Penpot более недоступен в flathub.

![image](https://github.com/user-attachments/assets/bb08012c-2b52-4567-8380-0087ed67ae24)

**Comment by Boria138** [comment]
К дополнению к этой ошибке, penpot desktop доступен в epm play о чём в статье не указано

**Comment by Ampernic** [comment]
Спасибо за дополнение, исправлено в https://github.com/OlegShchavelev/ALTGnomeWiki/commit/3aaf3fb60421d26f50a70a19af89f5b1b6b18fd9
