### ISSUE TITLE
Неверный линт инструмента `remark`

### ISSUE THREAD

**Issue by X1Z53** [OlegShchavelev/ALTGnomeWiki#611]
Инструмент [`remark`](https://github.com/remarkjs/remark-lint), используемый в проекте для проверки структуры файлов `.md`, а точнее его плагин [`remark-lint-no-multiple-toplevel-headings`](https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-multiple-toplevel-headings) воспринимает секцию метаданных (frontmatter) как часть документа

Если закоментировать строку в данной секции, то плагин вызывает ошибку о наличии нескольких заголовков верхнего уровня

Пример подобного поведения при добавлении комментария в секцию метаданных в файле [`docs/apps/penpot-desktop.md`](https://github.com/OlegShchavelev/ALTGnomeWiki/blob/main/docs/apps/penpot-desktop.md):

```
docs/apps/penpot-desktop.md
    5:3-5:23     warning Unexpected duplicate toplevel heading, exected a single heading with rank `1` no-multiple-toplevel-headings remark-lint
  [cause]:
    4:3-4:40 info    Toplevel heading already defined here no-multiple-toplevel-headings remark-lint
    25:1-25:17   warning Unexpected duplicate toplevel heading, exected a single heading with rank `1` no-multiple-toplevel-headings remark-lint
  [cause]:
    4:3-4:40 info    Toplevel heading already defined here no-multiple-toplevel-headings remark-lint
```

**Comment by Ampernic** [comment]
`remark` предназначен для обычного markdown из за чего это и возникло. 
Это глупый парсер который читает секцию фронтматтера так же как и обычную. 

Тут скорее моя ошибка в комментировании этих строк. Сейчас исправлю.

**Comment by Ampernic** [comment]
Исправил в https://github.com/OlegShchavelev/ALTGnomeWiki/commit/510e0dced0390ccbdc4571b2e47416854c4d8172
